use_default_settings: true

general:
  instance_name: "RobotAI Private Search"

search:
  safe_search: 0
  autocomplete: ""
  formats:
    - html
    - json

server:
  bind_address: "0.0.0.0"
  port: 8080
  secret_key: "d5620e123d01dcd9d798a400ad834449fb26f28edb0eea19d748198f3decad27"
  limiter: false
  image_proxy: false

outgoing:
  request_timeout: 3.0
  max_request_timeout: 6.0
