#ifndef _ROBOT_AI_PRIVATE_V1_CONFIG_H_
#define _ROBOT_AI_PRIVATE_V1_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE 16000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000
#define AUDIO_I2S_METHOD_SIMPLEX

#define AUDIO_I2S_MIC_GPIO_WS   GPIO_NUM_4
#define AUDIO_I2S_MIC_GPIO_SCK  GPIO_NUM_5
#define AUDIO_I2S_MIC_GPIO_DIN  GPIO_NUM_6

#define AUDIO_I2S_SPK_GPIO_DOUT GPIO_NUM_7
#define AUDIO_I2S_SPK_GPIO_BCLK GPIO_NUM_15
#define AUDIO_I2S_SPK_GPIO_LRCK GPIO_NUM_16

#define BOOT_BUTTON_GPIO GPIO_NUM_0
#define BUILTIN_LED_GPIO GPIO_NUM_48

#define DISPLAY_SPI_SCK_PIN  GPIO_NUM_9
#define DISPLAY_SPI_MOSI_PIN GPIO_NUM_10
#define DISPLAY_DC_PIN       GPIO_NUM_8
#define DISPLAY_RST_PIN      GPIO_NUM_18
#define DISPLAY_SPI_CS_PIN   GPIO_NUM_NC
#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_17
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false

#define DISPLAY_WIDTH  240
#define DISPLAY_HEIGHT 240
#define DISPLAY_OFFSET_X 0
#define DISPLAY_OFFSET_Y 0
#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false
#define DISPLAY_INVERT_COLOR true
#define DISPLAY_SPI_MODE 3

#define MOTOR_LEFT_IN1   GPIO_NUM_11
#define MOTOR_LEFT_IN2   GPIO_NUM_12
#define MOTOR_RIGHT_IN1  GPIO_NUM_13
#define MOTOR_RIGHT_IN2  GPIO_NUM_14

#define MOTOR_LEFT_POLARITY  1
#define MOTOR_RIGHT_POLARITY 1

#define TOF_SDA_PIN GPIO_NUM_41
#define TOF_SCL_PIN GPIO_NUM_42
#define TOF_I2C_ADDR 0x29

#define ROBOT_LED_A_GPIO GPIO_NUM_38
#define ROBOT_LED_B_GPIO GPIO_NUM_46

#define MOTOR_PWM_HZ 16000
#define MOTOR_MAX_DUTY 1023
#define MOTOR_DEFAULT_SPEED 38
#define MOTOR_TURN_SPEED 42
#define MOTOR_MAX_LINEAR_MS 1200
#define MOTOR_MAX_TURN_MS 3200
#define MOTOR_STOP_DISTANCE_MM 130
#define MOTOR_SPIN_360_DEFAULT_MS 1700

#define MAC_BRIDGE_DISCOVERY_PORT 8766
#define MAC_BRIDGE_HTTP_PORT 8765
#define ROBOT_ADMIN_PORT 8769
#define ROBOT_ADMIN_HELLO_PORT 8770
#define ROBOT_PUBLIC_XIAOZHI_OTA_URL "https://api.tenclass.net/xiaozhi/ota/"
// V6.8 build workflow injects ROBOT_ANYWHERE_OTA_URL when a public gateway URL is supplied.
// Do not hard-code a real secret URL in source control.
// Injected at build time from GitHub secret V68_MAC_BRIDGE_TOKEN.
#ifndef MAC_BRIDGE_TOKEN
#error "MAC_BRIDGE_TOKEN must be injected at build time"
#endif

#endif
